---

- name: install dependencies
  become: true
  apt:
    name: "{{ bbb_required_packages }}"
    update_cache: true

- name: set version of java to use
  become: true
  file:
    src: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
    dest: /etc/alternatives/java
    state: link

- name: Add NGINX sources
  become: true
  block:
    - name: "Install NGINX sources dependencies"
      apt:
        name: "software-properties-common"
        state: latest

    - name: "Add APT NGINX Signing Key"
      apt_key:
        url: "https://nginx.org/keys/nginx_signing.key"

    - name: "Add NGINX Repository"
      apt_repository:
        repo: "deb [arch=amd64] https://nginx.org/packages/{{ (bbb_nginx_use_mainline_branch|bool)
          | ternary('mainline/', '') }}{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} nginx"
  when: bbb_nginx_install_from_source|bool

- name: install nginx-full for client-logging
  become: true
  apt:
    name: nginx-full
    state: "{{ bbb_state }}"
    autoremove: true
    update_cache: true
  when: bbb_client_log_enable

- name: install nginx-core, no client-logging
  become: true
  apt:
    name: nginx-core
    state: "{{ bbb_state }}"
    autoremove: true
    update_cache: true
  when: not bbb_client_log_enable

- name: "Debug message regarding packages installation"
  debug:
    msg: "Installing bbb packages and dependencies, this may take a while..."

- name: install bbb and dependencies
  become: true
  apt:
    name: "{{ bbb_and_dependencies }}"
    state: "{{ bbb_state }}"
  notify: set bbb hostname

- name: install bbb-webhooks
  apt:
    name: "{{ bbb_webhooks }}"
    state: "{{ bbb_state }}"
  when: bbb_webhooks_enable
  notify: restart bigbluebutton

- name: install bbb api demos
  apt:
    name: "{{ bbb_demos }}"
    state: "{{ bbb_state }}"
  when: bbb_api_demos_enable

- name: remove bbb api demos
  apt:
    name: "{{ bbb_demos }}"
    state: "absent"
    # Using autoremove because otherwise tomcat8
    # would stay installed and keep running
    autoremove: true
  when: not bbb_api_demos_enable

- name: upgrade packages
  apt:
    upgrade: "{{ bbb_upgrade_packages }}"
  notify: set bbb hostname
