---
- name: Converge
  hosts: bbb
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"
  remote_user: root
  vars:
    bbb_nodejs_version: 8.x
    bbb_coturn_secret: ee8d093109a9b273
    bbb_greenlight_enable: false
    bbb_greenlight_secret: 107308d54ff4a5f
    bbb_greenlight_db_password: 2585c27c785e8895ec
    bbb_letsencrypt_enable: false
    bbb_letsencrypt_email: mail@example.com
  tasks:
    - name: "Include n0emis.bigbluebutton"
      include_role:
        name: "n0emis.bigbluebutton"
